### ISSUE TITLE
Migrating => Play 2.6 error: object recaptchaWidget is not a member of package views.html.recaptcha

### ISSUE THREAD

**Issue by bravegag** [chrisnappin/play-recaptcha-example#2]
While migrating a project to Play 2.6 I get the following error:
> error: object recaptchaWidget is not a member of package views.html.recaptcha
>

This among other errors I didn't have before:
>[error] /home/bravegag/code/play-authenticate-usage-scala/app/views/_recaptchaFieldPartial.scala.html:20: value isInternalErrorCode is not a member of object com.nappin.play.recaptcha.RecaptchaErrorCode
>[error] @recaptchaError = @{ errorCode.filter(code => !RecaptchaErrorCode.isInternalErrorCode(code)) }
>[error]                                                                   ^
>[error] /home/bravegag/code/play-authenticate-usage-scala/app/views/_recaptchaFieldPartial.scala.html:25: object recaptchaWidget is not a member of package views.html.recaptcha
>[error] Note: class recaptchaWidget exists, but it has no companion object.
>[error]         <div class="col-md-7">@recaptcha.recaptchaWidget(tabindex = tabindex, includeNoScript = includeNoScript)</div>
>[error]                                          ^
>[error] /home/bravegag/code/play-authenticate-usage-scala/app/views/_recaptchaFieldPartial.scala.html:25: reassignment to val
>[error]         <div class="col-md-7">@recaptcha.recaptchaWidget(tabindex = tabindex, includeNoScript = includeNoScript)</div>
>[error]                                                                   ^
>[error] /home/bravegag/code/play-authenticate-usage-scala/app/views/_recaptchaFieldPartial.scala.html:25: reassignment to val
>[error]         <div class="col-md-7">@recaptcha.recaptchaWidget(tabindex = tabindex, includeNoScript = includeNoScript)</div>
>[error]                                                                                               ^

I'm using the latest 2.3 version.

The code I'm working on can be found here:
https://github.com/bravegag/play-authenticate-usage-scala/tree/migrate-play-2.6

**Comment by chrisnappin** [comment]
Hi, thanks for your interest in play-recaptcha. Did you close this issue because you solved the cause?
